version: '3.8'

services:

  cost-living:
    image: local/rapid-api-sidecar
    build: rapid-api-sidecar
    container_name: cost-living-api-side-car
    restart: always
    ports:
      - 3001:3001
    env_file:
      - cost-living.env

  currency-exchange:
    image: local/rapid-api-sidecar
    build: rapid-api-sidecar
    container_name: currency-exchange-api-side-car
    restart: always
    ports:
      - 3002:3002
    env_file:
      - currency-exchange.env
