openapi: 3.0.3
info:
  title: currency-exchange-service API
  version: "1.0"
servers:
- url: http://localhost:3002
  description: Currency Exchange API
paths:
  /exchange:
    get:
      tags:
      - Exchange Currency
      operationId: exchangeCurrency
      parameters:
      - name: from
        in: query
        required: true
        schema:
          type: string
      - name: to
        in: query
        required: true
        schema:
          type: string
      - name: q
        in: query
        required: true
        schema:
          type: number

      responses:
        "200":
          description: OK
          content:
            text/plain:              
              schema:
                type: number